update util.py line 386, close file explicitly
sqlalchemy/mako pull request #313
Opened 2020-02-18 17:48 UTC by Dutchtallman

after a succesful read, the file ``fp`` is not closed

2020-02-18 18:20 UTC, zzzeek requested changes
Hi -

The file is closed successfully in the finally: block.    I'm not sure what the purpose of this PR is, and it also has no tests which would be necessary; the test needs to definitely fail without the code change present, and then not fail with the code change present.  I don't see how that's possible here because the handle is in fact closed.

2020-02-18 18:20 UTC, zzzeek commented on mako/util.py
>          fp.close()
the file is closed right here

2020-02-18 18:38 UTC, Dutchtallman commented
Hi,
yes, you are right. I made a simple test:
def test():    try:        print("try")        f =
open(filename)        d = f.read()        return
d    except:        print("except")    finally:        print("finally")
            f.close()
a = test()
and indeed, the finally block is executed. I thought it would not due
to the ``return`` statement in the ``try`` block. Case closed
Thanks, 

On Tue, 2020-02-18 at 10:20 -0800, mike bayer wrote:
> @zzzeek requested changes on this pull request.
> 
> 
> Hi -
> 
> The file is closed successfully in the finally: block.    I'm not
> sure what the purpose of this PR is, and it also has no tests which
> would be necessary; the test needs to definitely fail without the
> code change present, and then not fail with the code change
> present.  I don't see how that's possible here because the handle is
> in fact closed.
> 
> 
> In mako/util.py:
> 
> > @@ -383,6 +383,7 @@ def read_file(path, mode="rb"):     fp =
> open(path, mode)     try:         data =
> fp.read()+        fp.close()          # after a succesful read, the
> file is not closed         return
> data     finally:         fp.close()
> the file is closed right here
> 
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> [
> {
> "@context": "http://schema.org",
> "@type": "EmailMessage",
> "potentialAction": {
> "@type": "ViewAction",
> "target": "
> https://github.com/sqlalchemy/mako/pull/313?email_source=notifications\u0026email_token=AIARBUU7LNCH2AZAENKRHD3RDQRG7A5CNFSM4KXJKICKYY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCV64UKQ#pullrequestreview-360565290
> ",
> "url": "
> https://github.com/sqlalchemy/mako/pull/313?email_source=notifications\u0026email_token=AIARBUU7LNCH2AZAENKRHD3RDQRG7A5CNFSM4KXJKICKYY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCV64UKQ#pullrequestreview-360565290
> ",
> "name": "View Pull Request"
> },
> "description": "View this Pull Request on GitHub",
> "publisher": {
> "@type": "Organization",
> "name": "GitHub",
> "url": "https://github.com"
> }
> }
> ]

2020-02-19 07:16 UTC, closed without merging

2020-02-19 07:17 UTC, Dutchtallman commented
Was a mistake. the original code works fine.