Use `pre-commit` as linter & Checker ✨
sqlalchemy/mako pull request #345
Opened 2021-10-25 22:11 UTC by yezz123

Based on this issue https://github.com/sqlalchemy/mako/issues/344, I was thinking about why not use `.pre-commit` as a linter and checker.

Easy way to check code and fix any issue related to code style and code linting, about the rules I use only simple and most used rules for linting, SQLalchemy's team is free to change the rules or use another one for linting.

__Note__: This is just a simple enhancement to repository structure.

2021-10-26 12:24 UTC, CaselIT requested changes
I'm personally -1 on some of these. 

In particular I prefer to keep the configuration out of .pre-commit so that one is free to use the same tools with other runners.

2021-10-26 12:24 UTC, CaselIT commented on .github/workflows/run-on-pr.yaml
> +          pre-commit run --all-files
this removes the test run, so maybe we can have this together with the current version

2021-10-26 12:24 UTC, CaselIT commented on .pre-commit-config.yaml
> +            args: ["--profile", "black"]
we use zimports so -1 here

2021-10-26 12:24 UTC, CaselIT commented on .pre-commit-config.yaml
> +                - --select=F403,F406,F821,T003
I think it makes more sense to keep the configuration in setup.cfg

2021-10-26 12:24 UTC, CaselIT commented on .pre-commit-config.yaml
> +            args: ["--in-place"]
this seems to run `autoflake`. zimports does mostly the same

2021-10-26 12:24 UTC, CaselIT commented on .pre-commit-config.yaml
> +            args: ["--target-version", "py37"]
please keep the current version. also the setting should be in pyproject.toml

2021-10-26 12:24 UTC, CaselIT commented on .pre-commit-config.yaml
> +                - --select=F403,F406,F821,T003
also tox is probably a better place for this

2021-10-26 12:24 UTC, CaselIT commented on .pre-commit-config.yaml
> +          - id: check-ast
not sure it's really needed. we use test for this

2021-10-26 12:25 UTC, CaselIT commented
Thanks for the work. I've left a review.

It's probably best to wait for @zzzeek on this also so a single set of changes can be done

2021-10-26 18:03 UTC, jvanasco commented on .pre-commit-config.yaml
> +                - --select=F403,F406,F821,T003
+1 to @CaselIT's suggestion on this.  I generally like the idea of linting/checking on a pre-commit hook, but those checks will often need to be run on-demand during development -- and configuring them within pre-commit would require them to be duplicated in other config files.

2021-11-30 05:51 UTC, bourke commented
Thanks for the contribution. As @CaselIT and @jvanasco mentioned above, this PR gives `pre-commit` more responsibility in our tooling than we're comfortable with — especially considering that we'd prefer to keep the configurations as consistent as we can across the sqlalchemy organisation. @zzzeek suggested that the configuration for [dogpile.cache](https://github.com/sqlalchemy/dogpile.cache/blob/fa0fa49ef07bf2bdfa9e68626a9de1668ea4691f/.pre-commit-config.yaml) would be a good reference point.

2021-12-08 21:49 UTC, bourke commented
Hey there -- closing this for now. Let me know if you want to take it back up.

2021-12-08 21:49 UTC, closed without merging