Add closing tag in include.
sqlalchemy/mako pull request #359
Opened 2022-04-05 07:25 UTC by maxking

Fixes #260

2022-04-05 18:32 UTC, zzzeek commented on doc/build/inheritance.rst
>      <%inherit file="base.mako">
need it here too

2022-04-05 18:32 UTC, zzzeek requested changes
this page still has some tags without a slash can you get those also?  thanks!

2022-04-05 18:32 UTC, zzzeek commented on doc/build/inheritance.rst
>      <%inherit file="parent.mako">
and here....thanks!

2022-04-08 05:36 UTC, maxking commented
Hopefully I got all the ones on this page.

2022-04-08 17:23 UTC, sqla-tester reviewed
OK, this is **sqla-tester** setting up my work on behalf of **zzzeek** to try to get revision 541f219237c47ab159a7bc36172044d503cd0c08 of this pull request into gerrit so we can run tests and reviews and stuff

2022-04-08 17:23 UTC, sqla-tester commented
New Gerrit review created for change 541f219237c47ab159a7bc36172044d503cd0c08: https://gerrit.sqlalchemy.org/c/sqlalchemy/mako/+/3777

2022-04-08 17:23 UTC, zzzeek commented
looks great, thanks

2022-04-08 18:46 UTC, sqla-tester commented
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/mako/+/3777 has been **merged**. Congratulations! :)

2022-04-08 18:47 UTC, closed without merging