Support the direct passing of dictionary literals.
sqlalchemy/mako pull request #414
Opened 2024-10-29 14:02 UTC by cocolato

Fix: https://github.com/sqlalchemy/mako/issues/400 and https://github.com/sqlalchemy/mako/issues/401

Support the direct passing of dictionary literals when calling functions and fix the errors caused by unexpected nested braces.

2024-10-29 14:31 UTC, cocolato commented
The regular expression used here might not be elegant, but there should be no problem in terms of functionality.

2024-10-31 15:42 UTC, sqla-tester reviewed
OK, this is **sqla-tester** setting up my work on behalf of **zzzeek** to try to get revision a08ff83a16f7821b59f06ccb448d702aecbe6b99 of this pull request into gerrit so we can run tests and reviews and stuff

2024-10-31 15:43 UTC, sqla-tester commented
New Gerrit review created for change a08ff83a16f7821b59f06ccb448d702aecbe6b99: https://gerrit.sqlalchemy.org/c/sqlalchemy/mako/+/5558

2024-11-06 23:54 UTC, zzzeek requested changes
some more tests to add.  obviously im nervous about this change since we have to keep reverting it.

2024-11-06 23:54 UTC, zzzeek commented on test/test_lexer.py
> +    def test_dict_expression(self):
can you uncomment the "_dont_test_dict_expression_issue_400" and "_dont_test_dict_expression_2_issue_400"  tests also?  these were the original tests

2024-11-11 03:13 UTC, cocolato commented
Sorry for the late reply. Now all the tests have passed.

2024-11-11 17:50 UTC, sqla-tester reviewed
OK, this is **sqla-tester** setting up my work on behalf of **zzzeek** to try to get revision c6aa6bef1926f16ff3bb9afca00cf58c1b572a39 of this pull request into gerrit so we can run tests and reviews and stuff

2024-11-11 17:50 UTC, sqla-tester commented
Patchset c6aa6bef1926f16ff3bb9afca00cf58c1b572a39 added to existing Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/mako/+/5558

2024-12-03 18:52 UTC, sqla-tester commented
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/mako/+/5558 has been **merged**. Congratulations! :)

2024-12-03 18:52 UTC, closed without merging

2024-12-03 18:56 UTC, zzzeek commented
im going to release mako 1.3.7 now with these two changes you did, leaving enough room in the week to revert if we have more reports of issues, thanks!